# Generated by Django 5.1.6 on 2026-03-09 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('tenancy', '0002_alter_organizationmember_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationmember',
            name='assigned_branch',
            field=models.ForeignKey(blank=True, help_text='Required for STAFF. Must be null for OWNER and ADMIN. Restricts the STAFF member to this branch only. Must belong to the same organization as this membership.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_members', to='branches.branch'),
        ),
    ]
