# Generated by Django 5.2.12 on 2026-03-31 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_constraints_and_stock_take_unique_in_progress'),
        ('purchase_orders', '0002_item_to_orgitem'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='purchaseorderline',
            constraint=models.CheckConstraint(condition=models.Q(('received_quantity__lte', models.F('ordered_quantity'))), name='po_line_received_lte_ordered'),
        ),
    ]
