# Generated by Django 5.2.12 on 2026-03-10 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('LOGIN_SUCCESS', 'Login Success'), ('LOGIN_FAILURE', 'Login Failure'), ('LOGOUT', 'Logout'), ('TOKEN_REFRESH', 'Token Refresh'), ('REFRESH_FAILURE', 'Refresh Failure'), ('RATE_LIMITED', 'Rate Limited')], max_length=20)),
                ('username', models.CharField(blank=True, max_length=150)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('reason', models.TextField(blank=True)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['event', 'occurred_at'], name='api_auth_au_event_1f6415_idx'), models.Index(fields=['username', 'occurred_at'], name='api_auth_au_usernam_54ed2f_idx'), models.Index(fields=['ip_address', 'occurred_at'], name='api_auth_au_ip_addr_9db0d2_idx')],
            },
        ),
    ]
