# Generated by Django 5.2.12 on 2026-04-01 00:00

from django.db import migrations


HARDEN_PUBLIC_SCHEMA_SQL = """
DO $$
DECLARE
    table_row RECORD;
BEGIN
    FOR table_row IN
        SELECT n.nspname AS schema_name, c.relname AS table_name
        FROM pg_class c
        JOIN pg_namespace n ON n.oid = c.relnamespace
        WHERE n.nspname = 'public'
          AND c.relkind IN ('r', 'p')
    LOOP
        EXECUTE format(
            'ALTER TABLE %I.%I ENABLE ROW LEVEL SECURITY',
            table_row.schema_name,
            table_row.table_name
        );
    END LOOP;

    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon') THEN
        EXECUTE 'REVOKE ALL ON ALL TABLES IN SCHEMA public FROM anon';
        EXECUTE 'REVOKE ALL ON ALL SEQUENCES IN SCHEMA public FROM anon';
        EXECUTE 'REVOKE ALL ON ALL FUNCTIONS IN SCHEMA public FROM anon';
        EXECUTE 'ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON TABLES FROM anon';
        EXECUTE 'ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON SEQUENCES FROM anon';
        EXECUTE 'ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON FUNCTIONS FROM anon';
    END IF;

    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'authenticated') THEN
        EXECUTE 'REVOKE ALL ON ALL TABLES IN SCHEMA public FROM authenticated';
        EXECUTE 'REVOKE ALL ON ALL SEQUENCES IN SCHEMA public FROM authenticated';
        EXECUTE 'REVOKE ALL ON ALL FUNCTIONS IN SCHEMA public FROM authenticated';
        EXECUTE 'ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON TABLES FROM authenticated';
        EXECUTE 'ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON SEQUENCES FROM authenticated';
        EXECUTE 'ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON FUNCTIONS FROM authenticated';
    END IF;
END
$$;
"""


class Migration(migrations.Migration):

    dependencies = [
        ("api_auth", "0002_passwordsettoken"),
        ("branches", "0001_initial"),
        ("branch_transfers", "0004_branchtransferline_dispatched_unit_cost"),
        ("goods_receipts", "0003_item_to_orgitem"),
        ("inventory", "0012_constraints_and_stock_take_unique_in_progress"),
        ("purchase_orders", "0003_constraints_and_stock_take_unique_in_progress"),
        ("quick_sales", "0001_initial"),
        ("suppliers", "0002_supplier_v1_upgrade"),
        ("tenancy", "0004_parentcompanymember"),
        ("token_blacklist", "0012_alter_outstandingtoken_user"),
    ]

    operations = [
        migrations.RunSQL(
            sql=HARDEN_PUBLIC_SCHEMA_SQL,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
