# Generated by Django 5.2.12 on 2026-03-30 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch_transfers', '0003_branchtransfer_dispatched_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchtransferline',
            name='dispatched_unit_cost',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
    ]
