# Generated by Django 5.2.12 on 2026-05-07 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_lot_tracking'),
        ('suppliers', '0003_supplier_code_unique_non_blank'),
        ('tenancy', '0006_organization_operational_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_preferred', models.BooleanField(default=False)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('lead_time_days', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('org_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_items', to='inventory.orgitem')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.organization')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_items', to='suppliers.supplier')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_preferred', True)), fields=('org_item',), name='unique_preferred_supplier_per_item')],
                'unique_together': {('supplier', 'org_item')},
            },
        ),
    ]
