# Generated by Django 5.2.12 on 2026-03-18 09:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_stock_take'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktake',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stocktakeline',
            name='counted_quantity',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Physical count entered by staff. Null means not yet counted.', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='stocktakeline',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='stocktakeline',
            name='snapshot_quantity',
            field=models.DecimalField(decimal_places=4, help_text='System quantity at time of start. Not updated on reopen.', max_digits=12),
        ),
    ]
