# Generated by Django 5.2.12 on 2026-03-26 04:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_stocktake_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktake',
            name='reopened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stocktake',
            name='reopened_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reopened_stock_takes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stocktake',
            name='snapshot_taken_at',
            field=models.DateTimeField(blank=True, help_text='When snapshot quantities were captured. Not updated on reopen.', null=True),
        ),
    ]
