# Generated by Django 5.2.12 on 2026-03-26 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_stock_take_audit_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktake',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('IN_PROGRESS', 'In Progress'), ('PENDING_APPROVAL', 'Pending Approval'), ('COMPLETED', 'Completed'), ('COMPLETED_WITH_VARIANCES', 'Completed with Variances'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=30),
        ),
    ]
