# Generated by Django 5.2.12 on 2026-03-30 06:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('inventory', '0010_add_completed_with_variances_status'),
        ('tenancy', '0004_parentcompanymember'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stockledger',
            name='unit_cost',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='stockledger',
            name='value_delta',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True),
        ),
        migrations.CreateModel(
            name='InventoryClosePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSING', 'Closing'), ('CLOSED', 'Closed')], db_index=True, default='OPEN', max_length=10)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('reopened_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_periods', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.organization')),
                ('reopened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reopened_periods', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryCloseSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_on_hand', models.DecimalField(decimal_places=4, max_digits=12)),
                ('average_unit_cost', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('latest_unit_cost', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('average_valuation', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('latest_valuation', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('valuation_basis', models.CharField(choices=[('AVCO', 'AVCO'), ('LATEST', 'Latest')], default='AVCO', max_length=10)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='branches.branch')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.orgitem')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.organization')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='inventory.inventorycloseperiod')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryCostState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_unit_cost', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('latest_unit_cost', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('last_receipt_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cost_states', to='branches.branch')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cost_states', to='inventory.orgitem')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.organization')),
            ],
        ),
        migrations.AddIndex(
            model_name='inventorycloseperiod',
            index=models.Index(fields=['organization', 'start_date'], name='inv_closeperiod_org_start_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorycloseperiod',
            index=models.Index(fields=['organization', 'end_date'], name='inv_closeperiod_org_end_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventorycloseperiod',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['OPEN', 'CLOSING', 'CLOSED'])), name='inventory_close_period_valid_status'),
        ),
        migrations.AlterUniqueTogether(
            name='inventorycloseperiod',
            unique_together={('organization', 'start_date', 'end_date')},
        ),
        migrations.AddIndex(
            model_name='inventoryclosesnapshot',
            index=models.Index(fields=['period', 'branch'], name='inv_snap_period_branch_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryclosesnapshot',
            index=models.Index(fields=['period', 'item'], name='inv_snap_period_item_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='inventoryclosesnapshot',
            unique_together={('period', 'branch', 'item')},
        ),
        migrations.AlterUniqueTogether(
            name='inventorycoststate',
            unique_together={('organization', 'branch', 'item')},
        ),
    ]
