# Generated by Django 5.2.12 on 2026-03-31 13:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('inventory', '0011_stockledger_unit_cost_stockledger_value_delta_and_more'),
        ('tenancy', '0004_parentcompanymember'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='stocktake',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'IN_PROGRESS')), fields=('organization', 'branch'), name='unique_in_progress_stock_take_per_branch'),
        ),
    ]
