# Generated by Django 5.2.12 on 2026-05-04 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch_transfers', '0004_branchtransferline_dispatched_unit_cost'),
        ('branches', '0001_initial'),
        ('goods_receipts', '0004_goodsreceipt_idempotency_key'),
        ('inventory', '0015_cycle_counting'),
        ('tenancy', '0006_organization_operational_settings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='orgitem',
            name='is_expiry_tracked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orgitem',
            name='is_lot_tracked',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='InventoryLotBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_code', models.CharField(max_length=100)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('manufacture_date', models.DateField(blank=True, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('available_qty', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lot_balances', to='branches.branch')),
                ('org_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lot_balances', to='inventory.orgitem')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.organization')),
            ],
        ),
        migrations.CreateModel(
            name='GoodsReceiptLineLotAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=12)),
                ('receipt_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lot_allocations', to='goods_receipts.goodsreceiptline')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_allocations', to='inventory.inventorylotbalance')),
            ],
        ),
        migrations.CreateModel(
            name='BranchTransferLineReceiveLotAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=12)),
                ('transfer_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receive_lot_allocations', to='branch_transfers.branchtransferline')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_receive_allocations', to='inventory.inventorylotbalance')),
            ],
        ),
        migrations.CreateModel(
            name='BranchTransferLineDispatchLotAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=12)),
                ('transfer_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_lot_allocations', to='branch_transfers.branchtransferline')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_dispatch_allocations', to='inventory.inventorylotbalance')),
            ],
        ),
        migrations.CreateModel(
            name='StockMovementLotAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=12)),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lot_allocations', to='inventory.stockledger')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movement_allocations', to='inventory.inventorylotbalance')),
            ],
        ),
        migrations.CreateModel(
            name='StockTakeLineLotAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('INCREASE', 'Increase'), ('DECREASE', 'Decrease')], max_length=10)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=12)),
                ('lot_code', models.CharField(blank=True, max_length=100)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('manufacture_date', models.DateField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_take_allocations', to='inventory.inventorylotbalance')),
                ('stock_take_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lot_allocations', to='inventory.stocktakeline')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_take_lot_allocations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='inventorylotbalance',
            index=models.Index(fields=['organization', 'branch', 'org_item', 'expiry_date', 'received_at'], name='inv_lotbal_fefo_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventorylotbalance',
            constraint=models.UniqueConstraint(fields=('organization', 'branch', 'org_item', 'lot_code'), name='unique_lot_balance_per_org_branch_item_code'),
        ),
        migrations.AddConstraint(
            model_name='inventorylotbalance',
            constraint=models.CheckConstraint(condition=models.Q(('available_qty__gte', 0)), name='lot_balance_non_negative_qty'),
        ),
    ]
